// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Intranet.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BlogContent> BlogContent { get; set; }

    public virtual DbSet<BlogMedia> BlogMedia { get; set; }

    public virtual DbSet<Departments> Departments { get; set; }

    public virtual DbSet<FeaturedCollaborators> FeaturedCollaborators { get; set; }

    public virtual DbSet<InternalNews> InternalNews { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BlogContent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BlogCont__3214EC07BA2CC85E");

            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Img)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("img");
            entity.Property(e => e.PageType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("General")
                .HasColumnName("pageType");
            entity.Property(e => e.Template)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("template");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("title");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.BlogContent)
                .HasForeignKey(d => d.IdUser)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__BlogConte__IdUse__787EE5A0");
        });

        modelBuilder.Entity<BlogMedia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BlogMedi__3214EC074F3FE06B");

            entity.Property(e => e.BlogContentId).HasColumnName("blogContentId");
            entity.Property(e => e.MediaType)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("mediaType");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("url");

            entity.HasOne(d => d.BlogContent).WithMany(p => p.BlogMedia)
                .HasForeignKey(d => d.BlogContentId)
                .HasConstraintName("FK__BlogMedia__blogC__7B5B524B");
        });

        modelBuilder.Entity<Departments>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC07F242658B");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<FeaturedCollaborators>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Featured__3214EC079170066F");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Photo)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("photo");
            entity.Property(e => e.Testimonial)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("testimonial");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.FeaturedCollaborators)
                .HasForeignKey(d => d.IdUser)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__FeaturedC__IdUse__59063A47");
        });

        modelBuilder.Entity<InternalNews>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Internal__3214EC07FCBFED80");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Img)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("img");
            entity.Property(e => e.Title).HasColumnName("title");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.InternalNews)
                .HasForeignKey(d => d.IdUser)
                .HasConstraintName("FK__InternalN__IdUse__59FA5E80");
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC070EB6EA82");

            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07AB1C956A");

            entity.HasIndex(e => new { e.Name, e.PayRollNumber }, "UQ_Users_Name_PayRollNumber").IsUnique();

            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnName("passwordHash");
            entity.Property(e => e.PayRollNumber).HasColumnName("payRollNumber");
            entity.Property(e => e.RefreshToken)
                .HasMaxLength(256)
                .HasColumnName("refreshToken");
            entity.Property(e => e.RefreshTokenExpiryTime).HasColumnName("refreshTokenExpiryTime");

            entity.HasOne(d => d.IdDepartmentNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.IdDepartment)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Users__IdDepartm__5AEE82B9");

            entity.HasOne(d => d.IdRoleNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.IdRole)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Users__IdRole__5BE2A6F2");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}