// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Intranet.Models;

public partial class BlogContent
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Template { get; set; }

    public string Img { get; set; }

    public string PageType { get; set; }

    public int? IdUser { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<BlogMedia> BlogMedia { get; set; } = new List<BlogMedia>();

    public virtual Users IdUserNavigation { get; set; }
}